# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加购物车时间'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='count',
            field=models.IntegerField(default=10, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
