# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consignee', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('nation', models.CharField(default='中国', max_length=50, verbose_name='国家')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('city', models.CharField(max_length=50, verbose_name='市区')),
                ('country', models.CharField(max_length=50, verbose_name='县区')),
                ('street', models.CharField(max_length=50, verbose_name='街道')),
                ('intro', models.TextField(verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='地址状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('header', models.ImageField(default='static/images/headers/default.jpg', upload_to='static/images/headers/', verbose_name='用户头像')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('phone', models.CharField(max_length=20, verbose_name='用户电话')),
                ('age', models.IntegerField(default=0, verbose_name='用户年龄')),
                ('gender', models.CharField(max_length=5, verbose_name='用户性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
